# Generated by Django 4.2.1 on 2023-05-29 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50, unique=True)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('rut', models.IntegerField(unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('activo', models.BooleanField()),
                ('genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='crud.genero')),
            ],
        ),
    ]
